### ISSUE TITLE
Parsing error when requests use default content type header.

### ISSUE THREAD

**Issue by betzrhodes** [electricimp/Rocky#17]
Incoming requests with the default content type header of application/x-www-form-urlencoded are not parsed correctly. Parsing results in a table with a key containing the request body and a blank value.

**Comment by dkozorez** [comment]
It looks like if there's no urlencoded header is specified, request body is not  parsed with urldecode by design. 
Method sequentially checks if one of following headers is specified and if one of them fits request body is processed correspondingly
 * application/json
 * application/x-www-form-urlencoded
 * multipart/form-data
If neither of those headers were found, body remains unparsed which is default strategy. 
Moreover, attempt to apply http,urldecode on already decoded body will turn it to a table with a key containing request body and an empty value.

**Comment by ppetrosh** [comment]
@betzrhodes, I'm confirming the same behavior. I don't see any issues on my use case either:

```
#require "rocky.class.nut:1.3.0"

app <- Rocky()

app.post("/", function(context) {
    server.log(context.req.body)
    context.send(200, "hi")
})
```

If you set no headers, request arrives as a string, if you specify *application/x-www-form-urlencoded*, you receive a table. Seems like an expected behavior. Doesn't it?

**Comment by ppetrosh** [comment]
@betzrhodes, can you please provide your test case or more information on how to reproduce the problem.

**Comment by betzrhodes** [comment]
https://gist.github.com/betzrhodes/4d61df06840b36d031fe551af3be2be0

**Comment by dkozorez** [comment]
@betzrhodes, thanks for the sample. Just looked at your sample and it looks like Rocky works just well, Try to pass "val1=one&val2=two"  as http.post last param, i.e. : 

`local req = http.post( (http.agenturl() + "/data"), {}, "val1=one&val2=two" )`

And, using "PrettyPrinter.class.nut:1.0.1", and adding 
`print(context.req.body);`
just after 
`server.log(context.req.body);`
You will get following output:

2017-02-09 21:07:19+0000 [Agent]  {
2017-02-09 21:07:19+0000 [Agent]      "val1": "one",
2017-02-09 21:07:19+0000 [Agent]      "val2": "two"
2017-02-09 21:07:19+0000 [Agent]  }

Seems legit, don't it? 
Moreover, as @ppetrosh  already mentioned,

>  if you specify application/x-www-form-urlencoded, you receive a table

Am I getting something wrong?

**Comment by ppetrosh** [comment]
@dkozorez, the problem is that the following code:

```
#require "rocky.class.nut:1.3.0"

local req = http.post( (http.agenturl() + "/data"), {}, "hello world!");
req.sendasync(function(res) {
    server.log(res.statuscode);
});

app <- Rocky();
app.post("/data", function(context) {
    server.log(context.req.body);
    foreach (k, v in context.req.headers) {
        server.log("  [ ] k = " + k + ", v = " + v);
    }
    context.send(200);
});
```

shows that the content type is *application/x-www-form-urlencoded*, while *context.req.body* is indeed a table.

**Comment by ppetrosh** [comment]
However this doesn't seem to be a bug as even according to the Rocky documentation https://github.com/electricimp/Rocky:

*If a content-type header was included in the request, and the content-type was set to application/json, application/x-www-form-urlencoded, or multipart/form-data; the body propery of the request will be a table representing the parsed data, rather than the raw body.*

**Comment by ppetrosh** [comment]
As discussed and agreed with @betzrhodes today, we need to slightly update the documentation:

1. Add an example with agent-to-agent communication with no headers set that uses *rawbody*.
2. Mention that by default, if nothing else is specified, the *application/x-www-form-urlencoded* is used. Which results in having results converted into a table (*body*).
