### ISSUE TITLE
Errors in .on/verb callbacks stops code execution, but don't throw errors

### ISSUE THREAD

**Issue by betzrhodes** [electricimp/Rocky#18]
Errors that are thrown in the callbacks for Rocky verb and .on methods can fail silently.  Code inside the callback stops executing, but user is not notified that an error happened.  When this happens it is very hard to track down the error.

**Comment by ppetrosh** [comment]
@betzrhodes, can you please provide a testcase? Thanks!

**Comment by ppetrosh** [comment]
What we can do is to add an error log to the default exception handler:

```
@@ -352,6 +352,7 @@ class Rocky {
     }

     function _defaultExceptionHandler(context, ex) {
+        server.error(ex);
         context.send(500, "Agent Error: " + ex);
     }
```

We can't throw an exception in this case as by design all handlers need to get executed regardless of an error in one of them.

With the proposed change the user will get notified of an error in this case.

@betzrhodes would it help?
